# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: autocommit-robot

on:
  schedule:
    - cron: "0-30 8-20 * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: A
          author_email: qwe1234567891473@outlook.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
