#test
name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 8 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green 1
        run: |
          git config --local user.email "qwe1234567891473@outlook.com"
          git config --local user.name "wxq1884482"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
